export const projects = [
   {
      name: "Create Next App",
      description: "Generated by create next app",
      path: " ",
   },
   {
      name: "Create Next App",
      description: "Generated by create next app",
      path: " ",
   },
   ];