export const projects = [
   {
      title: "Create Next App",
      description: "Generated by create next app",
   },
   {
      title: "Tailwind CSS",
      description: "A utility-first CSS framework for rapidly building custom designs.",
   },
   {
      title: "React",
      description: "A JavaScript library for building user interfaces.",
   },
   {
      title: "TypeScript",
      description: "A typed superset of JavaScript that compiles to plain JavaScript.",
   },
   {
      title: "Vercel",
      description: "Develop. Preview. Ship.",
   },
   ];